### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by gamename** [tampajohn/slack-upvote#1]
Hi,

This looks really cool. But how do you install it? :)

**Comment by tampajohn** [comment]
I use a free Horoku dyno with a Mongolab free account... I should probably
write some installation instructions for it. Want me to do that?

**Comment by gamename** [comment]
Thank you, sir. That would be great.  Not familiar with either Horoku or Mongolab.

**Comment by tampajohn** [comment]
Honestly, if you want to just use the default server we setup to try it out, all you need to do is add an Outgoing Webhook integration in slack:

Channel: Any
Trigger Word(s): +,-,?
URL(s): slackvote.herokuapp.com
Token: (a randomly generated token for your team)
Descriptive Label: (Anything)
Customize Name: (Anything)
Customize Icon: (Anything)

**Comment by tampajohn** [comment]
To support slash commands (secret voting) simply add:

a slash command for /up pointing to http://slackvote.herokuapp.com
a slash command for /down pointing to http://slackvote.herokuapp.com

I find we really don't use these much, so might be removing them in the future.

**Comment by davidlfox** [comment]
Does the mongolab db need to be setup a specific way e.g. db name, permissions? I added a db, an owner, a **slack-upvote** collection, and a heroku config value called SLACKVOTE_DB with the value mongolab specified, and it doesn't appear my docs are being inserted.

**Comment by tampajohn** [comment]
Sounds right to me...

Does your user have write permissions?

My SLACKVOTE_DB is of this format:

mongodb://slackhook:password@ds053300.mongolab.com:53300/slack-upvote

and my user
:[image: Inline image 1]

**Comment by TeflonDon94** [comment]
Hey @tampajohn,

I've noticed that your app is still online, but does not keep track of the votes anymore.
I tried to create a heroku and mlab connection myself, but as a non-developer it's a bit too tedious to do on my business hours.

Could you perhaps give me a bit of the logical steps without deeper explanation? The guides for heroku are so broad that you get lost easily.

Thanks.
